name: Tests
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/.eslintcache
            **/.jest-cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn install --network-concurrency 1 --frozen-lockfile
          on_retry_command: yarn cache clean
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test --cacheDirectory .jest-cache
